import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {TTNormal, TT_C_Normal, TTMono} from "./fonts";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body
                className={`${TTNormal.variable} ${TT_C_Normal.variable} ${TTMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
